-- Applies font-family, font-style, and/or font-size overrides to ::: font divs and [text]{.font} spans.
-- See README.md for usage. All font declarations (LaTeX and CSS) are generated by
-- keystone.lua from the shared font registry.

local kast = ks_require("ast")

-- Build lookup maps from the shared font registry (see docs/pandoc-integration/README.md#registries).
local font_registry = ks_require("font-registry")

-- family_map: user-facing names → LaTeX commands
local family_map = {}
for name, font in pairs(font_registry.fonts) do
  family_map[name] = font.command
end

-- size_map: user-facing names → LaTeX size commands
local size_map = font_registry.latex_size_map()

-- docx_family_map: registry key → font style ID prefix (e.g. "libertine" → "font:georgia")
local docx_family_map = {}
for name in pairs(font_registry.fonts) do
  local fallback = font_registry.system_fallback(name)
  if fallback then
    docx_family_map[name] = font_registry.font_style_id(fallback)
  end
end

-- docx_size_map: user-facing name → em value string (e.g. "small" → "0.9")
-- Uses em values because OOXML style lookups are case-insensitive,
-- making large/Large/LARGE collide when using names directly.
local docx_size_map = {}
for _, entry in ipairs(font_registry.sizes) do
  docx_size_map[entry.name] = font_registry.size_em_value(entry.name)
end

-- Scope-based LaTeX declarations for font style.
-- Placed inside the same \begingroup / {...} scope as the family switch,
-- so the style declaration is not reset by fontspec's family change.
local STYLE_MAP = {
  ["italic"] = "\\itshape",
  ["bold"] = "\\bfseries",
  ["bold-italic"] = "\\bfseries\\itshape",
}

-- ── Shared validation ────────────────────────────────────────────────

--- Validate family/style/size attributes against their lookup tables.
--- Returns resolved family_key, style, size (any may be nil) or nil on error.
--- Warns on unknown values and returns nil to signal the handler should bail.
local function validate_attrs(el)
  local family = el.attributes["family"]
  local style = el.attributes["style"]
  local size = el.attributes["size"]
  if not family and not style and not size then return nil end

  local family_key
  if family then
    family_key = family:lower()
    if not family_map[family_key] then
      io.stderr:write("WARN: font: unknown family '" .. family .. "'\n")
      return nil
    end
  end

  if style and not STYLE_MAP[style] then
    io.stderr:write("WARN: font: unknown style '" .. style .. "'\n")
    return nil
  end

  if size and not size_map[size] then
    io.stderr:write("WARN: font: unknown size '" .. size .. "'\n")
    return nil
  end

  return family_key, style, size
end

-- ── LaTeX ────────────────────────────────────────────────────────────

local function div_latex(el)
  local family_key, style, size = validate_attrs(el)
  if not family_key and not style and not size then return nil end

  local parts = {}
  if family_key then parts[#parts + 1] = family_map[family_key] end
  if style then parts[#parts + 1] = STYLE_MAP[style] end
  if size then parts[#parts + 1] = size_map[size] end

  local blocks = {}
  blocks[#blocks + 1] = kast.RawBlock("latex", "\\begingroup" .. table.concat(parts))
  for _, block in ipairs(el.content) do
    blocks[#blocks + 1] = block
  end
  blocks[#blocks + 1] = kast.RawBlock("latex", "\\endgroup")
  return blocks
end

local function span_latex(el)
  local family_key, style, size = validate_attrs(el)
  if not family_key and not style and not size then return nil end

  local parts = {}
  if family_key then parts[#parts + 1] = family_map[family_key] end
  if style then parts[#parts + 1] = STYLE_MAP[style] end
  if size then parts[#parts + 1] = size_map[size] end

  local inlines = kast.List({})
  inlines:insert(kast.RawInline("latex", "{" .. table.concat(parts) .. " "))
  inlines:extend(el.content)
  inlines:insert(kast.RawInline("latex", "}"))
  return inlines
end

-- ── HTML / EPUB ──────────────────────────────────────────────────────

local function html(el)
  local family_key, style, size = validate_attrs(el)
  if not family_key and not style and not size then return nil end

  local classes = {}
  if family_key then
    classes[#classes + 1] = "font-family-" .. family_key
    el.attributes["family"] = nil
  end
  if style then
    classes[#classes + 1] = "style-" .. style
    el.attributes["style"] = nil
  end
  if size then
    classes[#classes + 1] = "font-size-" .. size
    el.attributes["size"] = nil
  end
  el.classes = classes
  return el
end

-- ── DOCX / ODT ───────────────────────────────────────────────────────

--- Build a colon-delimited custom-style ID from family/style/size.
--- Segment order: font:style:size. The leading segment carries a category
--- prefix (font:, style:, or size:) that identifies the ID type.
local function resolve_docx_style(el)
  local family_key, style, size = validate_attrs(el)
  if not family_key and not style and not size then return nil end

  local font_prefix = family_key and docx_family_map[family_key]
  if family_key and not font_prefix then return nil end

  local em_value = size and docx_size_map[size]
  if size and not em_value then return nil end

  -- Pick category prefix, then append optional segments
  local segments = {}
  if font_prefix then
    segments[#segments + 1] = font_prefix
    if style then segments[#segments + 1] = style end
  elseif style then
    segments[#segments + 1] = "style:" .. style
  else
    segments[#segments + 1] = "size:" .. em_value
    return table.concat(segments, ":")
  end
  if em_value then segments[#segments + 1] = em_value end

  return table.concat(segments, ":")
end

local function apply_docx_style(el, is_para)
  local style_id = resolve_docx_style(el)
  if not style_id then return nil end

  el.attributes["custom-style"] = is_para and (style_id .. ":para") or style_id
  el.attributes["family"] = nil
  el.attributes["style"] = nil
  el.attributes["size"] = nil
  return el
end

local function div_docx(el)
  return apply_docx_style(el, true)
end

local function span_docx(el)
  return apply_docx_style(el, false)
end

return {
  div = {
    latex = div_latex,
    html = html,
    epub = html,
    docx = div_docx,
    odt = div_docx,
  },
  span = {
    latex = span_latex,
    html = html,
    epub = html,
    docx = span_docx,
    odt = span_docx,
  },
}
