-- Applies font-family and/or font-size overrides to ::: font divs and [text]{.font} spans.
-- See README.md for usage. All font declarations (LaTeX and CSS) are generated by
-- keystone.lua from the shared font registry.

-- Build lookup maps from the shared font registry (see docs/pandoc-integration.md § Font Registry).
local font_registry = dofile(pandoc.path.join({ KEYSTONE_FILTERS_DIR, "lib", "font-registry.lua" }))

-- family_map: user-facing names → LaTeX commands
local family_map = {}
for name, font in pairs(font_registry.fonts) do
  family_map[name] = font.command
end

-- size_map: user-facing names → LaTeX size commands
local size_map = font_registry.latex_size_map()

return {
  div = function(el)
    local family = el.attributes["family"]
    local size = el.attributes["size"]
    if not family and not size then return nil end

    if FORMAT:match("latex") then
      local parts = {}

      if family then
        local key = family:lower()
        local cmd = family_map[key]
        if not cmd then
          io.stderr:write("WARN: font: unknown family '" .. family .. "'\n")
          return nil
        end
        table.insert(parts, cmd)
      end

      if size then
        local cmd = size_map[size]
        if not cmd then
          io.stderr:write("WARN: font: unknown size '" .. size .. "'\n")
          return nil
        end
        table.insert(parts, cmd)
      end

      local blocks = {}
      table.insert(blocks, pandoc.RawBlock("latex", "\\begingroup" .. table.concat(parts)))
      for _, block in ipairs(el.content) do
        table.insert(blocks, block)
      end
      table.insert(blocks, pandoc.RawBlock("latex", "\\endgroup"))
      return blocks
    elseif FORMAT:match("html") or FORMAT:match("epub") then
      local classes = {}
      if family then
        local key = family:lower()
        table.insert(classes, "font-family-" .. key)
        el.attributes["family"] = nil
      end
      if size then
        table.insert(classes, "font-size-" .. size)
        el.attributes["size"] = nil
      end
      el.classes = classes
      return el
    end
  end,

  span = function(el)
    local family = el.attributes["family"]
    local size = el.attributes["size"]
    if not family and not size then return nil end

    if FORMAT:match("latex") then
      local parts = {}

      if family then
        local key = family:lower()
        local cmd = family_map[key]
        if not cmd then
          io.stderr:write("WARN: font: unknown family '" .. family .. "'\n")
          return nil
        end
        table.insert(parts, cmd)
      end

      if size then
        local cmd = size_map[size]
        if not cmd then
          io.stderr:write("WARN: font: unknown size '" .. size .. "'\n")
          return nil
        end
        table.insert(parts, cmd)
      end

      local inlines = pandoc.List({})
      inlines:insert(pandoc.RawInline("latex", "{" .. table.concat(parts) .. " "))
      inlines:extend(el.content)
      inlines:insert(pandoc.RawInline("latex", "}"))
      return inlines
    elseif FORMAT:match("html") or FORMAT:match("epub") then
      local classes = {}
      if family then
        local key = family:lower()
        table.insert(classes, "font-family-" .. key)
        el.attributes["family"] = nil
      end
      if size then
        table.insert(classes, "font-size-" .. size)
        el.attributes["size"] = nil
      end
      el.classes = classes
      return el
    end
  end,
}
